analyzer:
  errors:
    constant_identifier_names: ignore
    file_names: ignore
    no_leading_underscores_for_local_identifiers: ignore
    unused_element: ignore
    unused_local_variable: ignore
include: package:flutter_lints/flutter.yaml
